writingthread = false
writingthread.observe = null
writingthread.priority = 1

writer = e logger

writer.format = ${APP_NAME} [{level}] {date:yyyy-MM-dd HH:mm:ss.SSS} {package}.{class-name}.{method}: {message} ##EXCEPTION##
writer.level = ${LOG_LEVEL}

level@org.jaudiotagger = ERROR
level@cl.estencia.labs.ebot.bus = OFF

locale = es_CL