writingthread = false
writingthread.observe = null
writingthread.priority = 1

writer = e logger

writer.format = ${APP_NAME} [{level}] {date:yyyy-MM-dd HH:mm:ss} {package}.{class-name}.{method}: {message} ##EXCEPTION##
writer.level = ${LOG_LEVEL}

level@cl.estencia.labs.ebot.bus = OFF
level@cl.estencia.labs.ebot.utils = OFF
level@org.jaudiotagger = ERROR
level@org.freedesktop.dbus = ERROR

locale = es_CL